# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import RL_pb2 as rpc_dot_RL__pb2


class ActorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRegrets = channel.unary_unary(
                '/Actor/GetRegrets',
                request_serializer=rpc_dot_RL__pb2.Observation.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Prediction.FromString,
                )
        self.GetStrategies = channel.unary_unary(
                '/Actor/GetStrategies',
                request_serializer=rpc_dot_RL__pb2.Observation.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Prediction.FromString,
                )
        self.SetStrategy = channel.unary_unary(
                '/Actor/SetStrategy',
                request_serializer=rpc_dot_RL__pb2.Selection.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class ActorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRegrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRegrets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegrets,
                    request_deserializer=rpc_dot_RL__pb2.Observation.FromString,
                    response_serializer=rpc_dot_RL__pb2.Prediction.SerializeToString,
            ),
            'GetStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategies,
                    request_deserializer=rpc_dot_RL__pb2.Observation.FromString,
                    response_serializer=rpc_dot_RL__pb2.Prediction.SerializeToString,
            ),
            'SetStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStrategy,
                    request_deserializer=rpc_dot_RL__pb2.Selection.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Actor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Actor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRegrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Actor/GetRegrets',
            rpc_dot_RL__pb2.Observation.SerializeToString,
            rpc_dot_RL__pb2.Prediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Actor/GetStrategies',
            rpc_dot_RL__pb2.Observation.SerializeToString,
            rpc_dot_RL__pb2.Prediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Actor/SetStrategy',
            rpc_dot_RL__pb2.Selection.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class LearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRegrets = channel.unary_unary(
                '/Learner/AddRegrets',
                request_serializer=rpc_dot_RL__pb2.SampledData.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.AddStrategies = channel.unary_unary(
                '/Learner/AddStrategies',
                request_serializer=rpc_dot_RL__pb2.SampledData.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.TrainRegrets = channel.unary_unary(
                '/Learner/TrainRegrets',
                request_serializer=rpc_dot_RL__pb2.Who.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.TrainStrategy = channel.unary_unary(
                '/Learner/TrainStrategy',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class LearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRegrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainRegrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRegrets': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRegrets,
                    request_deserializer=rpc_dot_RL__pb2.SampledData.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'AddStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStrategies,
                    request_deserializer=rpc_dot_RL__pb2.SampledData.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'TrainRegrets': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainRegrets,
                    request_deserializer=rpc_dot_RL__pb2.Who.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'TrainStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainStrategy,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Learner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Learner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRegrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/AddRegrets',
            rpc_dot_RL__pb2.SampledData.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/AddStrategies',
            rpc_dot_RL__pb2.SampledData.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainRegrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/TrainRegrets',
            rpc_dot_RL__pb2.Who.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/TrainStrategy',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompleteTraversal = channel.unary_unary(
                '/Master/CompleteTraversal',
                request_serializer=rpc_dot_RL__pb2.Identifier.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompleteTraversal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompleteTraversal': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTraversal,
                    request_deserializer=rpc_dot_RL__pb2.Identifier.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompleteTraversal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/CompleteTraversal',
            rpc_dot_RL__pb2.Identifier.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class SlaveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetIdentifier = channel.unary_unary(
                '/Slave/SetIdentifier',
                request_serializer=rpc_dot_RL__pb2.Identifier.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.RunIterations = channel.unary_unary(
                '/Slave/RunIterations',
                request_serializer=rpc_dot_RL__pb2.IterationSettings.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.RunEvaluations = channel.unary_unary(
                '/Slave/RunEvaluations',
                request_serializer=rpc_dot_RL__pb2.EvaluationSettings.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class SlaveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetIdentifier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunIterations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvaluations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlaveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetIdentifier': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIdentifier,
                    request_deserializer=rpc_dot_RL__pb2.Identifier.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'RunIterations': grpc.unary_unary_rpc_method_handler(
                    servicer.RunIterations,
                    request_deserializer=rpc_dot_RL__pb2.IterationSettings.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'RunEvaluations': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEvaluations,
                    request_deserializer=rpc_dot_RL__pb2.EvaluationSettings.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Slave', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Slave(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetIdentifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Slave/SetIdentifier',
            rpc_dot_RL__pb2.Identifier.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunIterations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Slave/RunIterations',
            rpc_dot_RL__pb2.IterationSettings.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunEvaluations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Slave/RunEvaluations',
            rpc_dot_RL__pb2.EvaluationSettings.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
