# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/RL.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/RL.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0crpc/RL.proto\"w\n\x0bObservation\x12\x0e\n\x06player\x18\x01 \x01(\x05\x12\x14\n\x0cobservations\x18\x02 \x01(\x0c\x12\x1a\n\x12observation_counts\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x01(\x05\x12\x17\n\x0fsequence_length\x18\x05 \x01(\x05\"?\n\nPrediction\x12\x19\n\x11\x61\x63tion_prediction\x18\x01 \x01(\x0c\x12\x16\n\x0e\x62\x65t_prediction\x18\x02 \x01(\x0c\"\x9e\x01\n\x0bSampledData\x12\x0e\n\x06player\x18\x01 \x01(\x05\x12\x14\n\x0cobservations\x18\x02 \x01(\x0c\x12\x1a\n\x12observation_counts\x18\x03 \x01(\x0c\x12\x13\n\x0b\x61\x63tion_data\x18\x04 \x01(\x0c\x12\x10\n\x08\x62\x65t_data\x18\x05 \x01(\x0c\x12\r\n\x05shape\x18\x06 \x01(\x05\x12\x17\n\x0fsequence_length\x18\x07 \x01(\x05\"\x15\n\x03Who\x12\x0e\n\x06player\x18\x01 \x01(\x05\"5\n\tSelection\x12\x0e\n\x06player\x18\x01 \x01(\x05\x12\x18\n\x10strategy_version\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty\"S\n\x11IterationSettings\x12\t\n\x01k\x18\x01 \x01(\x05\x12\x1e\n\x16traversals_per_process\x18\x02 \x01(\x05\x12\x13\n\x0bn_processes\x18\x03 \x01(\x05\"\x14\n\x12\x45valuationSettings\"\x1f\n\nIdentifier\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x32\x7f\n\x05\x41\x63tor\x12\'\n\nGetRegrets\x12\x0c.Observation\x1a\x0b.Prediction\x12*\n\rGetStrategies\x12\x0c.Observation\x1a\x0b.Prediction\x12!\n\x0bSetStrategy\x12\n.Selection\x1a\x06.Empty2\x93\x01\n\x07Learner\x12\"\n\nAddRegrets\x12\x0c.SampledData\x1a\x06.Empty\x12%\n\rAddStrategies\x12\x0c.SampledData\x1a\x06.Empty\x12\x1c\n\x0cTrainRegrets\x12\x04.Who\x1a\x06.Empty\x12\x1f\n\rTrainStrategy\x12\x06.Empty\x1a\x06.Empty22\n\x06Master\x12(\n\x11\x43ompleteTraversal\x12\x0b.Identifier\x1a\x06.Empty2\x89\x01\n\x05Slave\x12$\n\rSetIdentifier\x12\x0b.Identifier\x1a\x06.Empty\x12+\n\rRunIterations\x12\x12.IterationSettings\x1a\x06.Empty\x12-\n\x0eRunEvaluations\x12\x13.EvaluationSettings\x1a\x06.Emptyb\x06proto3'
)




_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='Observation.player', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observations', full_name='Observation.observations', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observation_counts', full_name='Observation.observation_counts', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='Observation.shape', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_length', full_name='Observation.sequence_length', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=135,
)


_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_prediction', full_name='Prediction.action_prediction', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bet_prediction', full_name='Prediction.bet_prediction', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=200,
)


_SAMPLEDDATA = _descriptor.Descriptor(
  name='SampledData',
  full_name='SampledData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='SampledData.player', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observations', full_name='SampledData.observations', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observation_counts', full_name='SampledData.observation_counts', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_data', full_name='SampledData.action_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bet_data', full_name='SampledData.bet_data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='SampledData.shape', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_length', full_name='SampledData.sequence_length', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=361,
)


_WHO = _descriptor.Descriptor(
  name='Who',
  full_name='Who',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='Who.player', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=384,
)


_SELECTION = _descriptor.Descriptor(
  name='Selection',
  full_name='Selection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='Selection.player', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strategy_version', full_name='Selection.strategy_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=439,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=448,
)


_ITERATIONSETTINGS = _descriptor.Descriptor(
  name='IterationSettings',
  full_name='IterationSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='IterationSettings.k', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traversals_per_process', full_name='IterationSettings.traversals_per_process', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_processes', full_name='IterationSettings.n_processes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=533,
)


_EVALUATIONSETTINGS = _descriptor.Descriptor(
  name='EvaluationSettings',
  full_name='EvaluationSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=555,
)


_IDENTIFIER = _descriptor.Descriptor(
  name='Identifier',
  full_name='Identifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='Identifier.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=588,
)

DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
DESCRIPTOR.message_types_by_name['SampledData'] = _SAMPLEDDATA
DESCRIPTOR.message_types_by_name['Who'] = _WHO
DESCRIPTOR.message_types_by_name['Selection'] = _SELECTION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['IterationSettings'] = _ITERATIONSETTINGS
DESCRIPTOR.message_types_by_name['EvaluationSettings'] = _EVALUATIONSETTINGS
DESCRIPTOR.message_types_by_name['Identifier'] = _IDENTIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:Observation)
  })
_sym_db.RegisterMessage(Observation)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:Prediction)
  })
_sym_db.RegisterMessage(Prediction)

SampledData = _reflection.GeneratedProtocolMessageType('SampledData', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEDDATA,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:SampledData)
  })
_sym_db.RegisterMessage(SampledData)

Who = _reflection.GeneratedProtocolMessageType('Who', (_message.Message,), {
  'DESCRIPTOR' : _WHO,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:Who)
  })
_sym_db.RegisterMessage(Who)

Selection = _reflection.GeneratedProtocolMessageType('Selection', (_message.Message,), {
  'DESCRIPTOR' : _SELECTION,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:Selection)
  })
_sym_db.RegisterMessage(Selection)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

IterationSettings = _reflection.GeneratedProtocolMessageType('IterationSettings', (_message.Message,), {
  'DESCRIPTOR' : _ITERATIONSETTINGS,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:IterationSettings)
  })
_sym_db.RegisterMessage(IterationSettings)

EvaluationSettings = _reflection.GeneratedProtocolMessageType('EvaluationSettings', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONSETTINGS,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationSettings)
  })
_sym_db.RegisterMessage(EvaluationSettings)

Identifier = _reflection.GeneratedProtocolMessageType('Identifier', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIER,
  '__module__' : 'rpc.RL_pb2'
  # @@protoc_insertion_point(class_scope:Identifier)
  })
_sym_db.RegisterMessage(Identifier)



_ACTOR = _descriptor.ServiceDescriptor(
  name='Actor',
  full_name='Actor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=590,
  serialized_end=717,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRegrets',
    full_name='Actor.GetRegrets',
    index=0,
    containing_service=None,
    input_type=_OBSERVATION,
    output_type=_PREDICTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetStrategies',
    full_name='Actor.GetStrategies',
    index=1,
    containing_service=None,
    input_type=_OBSERVATION,
    output_type=_PREDICTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetStrategy',
    full_name='Actor.SetStrategy',
    index=2,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTOR)

DESCRIPTOR.services_by_name['Actor'] = _ACTOR


_LEARNER = _descriptor.ServiceDescriptor(
  name='Learner',
  full_name='Learner',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=720,
  serialized_end=867,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddRegrets',
    full_name='Learner.AddRegrets',
    index=0,
    containing_service=None,
    input_type=_SAMPLEDDATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddStrategies',
    full_name='Learner.AddStrategies',
    index=1,
    containing_service=None,
    input_type=_SAMPLEDDATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainRegrets',
    full_name='Learner.TrainRegrets',
    index=2,
    containing_service=None,
    input_type=_WHO,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainStrategy',
    full_name='Learner.TrainStrategy',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEARNER)

DESCRIPTOR.services_by_name['Learner'] = _LEARNER


_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='Master',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=869,
  serialized_end=919,
  methods=[
  _descriptor.MethodDescriptor(
    name='CompleteTraversal',
    full_name='Master.CompleteTraversal',
    index=0,
    containing_service=None,
    input_type=_IDENTIFIER,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER


_SLAVE = _descriptor.ServiceDescriptor(
  name='Slave',
  full_name='Slave',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=922,
  serialized_end=1059,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetIdentifier',
    full_name='Slave.SetIdentifier',
    index=0,
    containing_service=None,
    input_type=_IDENTIFIER,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunIterations',
    full_name='Slave.RunIterations',
    index=1,
    containing_service=None,
    input_type=_ITERATIONSETTINGS,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunEvaluations',
    full_name='Slave.RunEvaluations',
    index=2,
    containing_service=None,
    input_type=_EVALUATIONSETTINGS,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLAVE)

DESCRIPTOR.services_by_name['Slave'] = _SLAVE

# @@protoc_insertion_point(module_scope)
