# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import RL_pb2 as rpc_dot_RL__pb2


class ActorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRegrets = channel.unary_unary(
                '/Actor/GetRegrets',
                request_serializer=rpc_dot_RL__pb2.Observation.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Prediction.FromString,
                )
        self.GetStrategies = channel.unary_unary(
                '/Actor/GetStrategies',
                request_serializer=rpc_dot_RL__pb2.Observation.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Prediction.FromString,
                )
        self.SetStrategy = channel.unary_unary(
                '/Actor/SetStrategy',
                request_serializer=rpc_dot_RL__pb2.Selection.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class ActorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRegrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRegrets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegrets,
                    request_deserializer=rpc_dot_RL__pb2.Observation.FromString,
                    response_serializer=rpc_dot_RL__pb2.Prediction.SerializeToString,
            ),
            'GetStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategies,
                    request_deserializer=rpc_dot_RL__pb2.Observation.FromString,
                    response_serializer=rpc_dot_RL__pb2.Prediction.SerializeToString,
            ),
            'SetStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStrategy,
                    request_deserializer=rpc_dot_RL__pb2.Selection.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Actor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Actor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRegrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Actor/GetRegrets',
            rpc_dot_RL__pb2.Observation.SerializeToString,
            rpc_dot_RL__pb2.Prediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Actor/GetStrategies',
            rpc_dot_RL__pb2.Observation.SerializeToString,
            rpc_dot_RL__pb2.Prediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Actor/SetStrategy',
            rpc_dot_RL__pb2.Selection.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class RegretLearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRegrets = channel.unary_unary(
                '/RegretLearner/AddRegrets',
                request_serializer=rpc_dot_RL__pb2.SampledData.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.TrainRegrets = channel.unary_unary(
                '/RegretLearner/TrainRegrets',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.AvailableStrategies = channel.unary_unary(
                '/RegretLearner/AvailableStrategies',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )


class RegretLearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRegrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainRegrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegretLearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRegrets': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRegrets,
                    request_deserializer=rpc_dot_RL__pb2.SampledData.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'TrainRegrets': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainRegrets,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'AvailableStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableStrategies,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RegretLearner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegretLearner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRegrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegretLearner/AddRegrets',
            rpc_dot_RL__pb2.SampledData.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainRegrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegretLearner/TrainRegrets',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AvailableStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegretLearner/AvailableStrategies',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class StrategyLearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStrategies = channel.unary_unary(
                '/StrategyLearner/AddStrategies',
                request_serializer=rpc_dot_RL__pb2.SampledData.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.TrainStrategy = channel.unary_unary(
                '/StrategyLearner/TrainStrategy',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.AvailableStrategies = channel.unary_unary(
                '/StrategyLearner/AvailableStrategies',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )


class StrategyLearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyLearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStrategies,
                    request_deserializer=rpc_dot_RL__pb2.SampledData.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'TrainStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainStrategy,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'AvailableStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableStrategies,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StrategyLearner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StrategyLearner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StrategyLearner/AddStrategies',
            rpc_dot_RL__pb2.SampledData.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StrategyLearner/TrainStrategy',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AvailableStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StrategyLearner/AvailableStrategies',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class EvalPPOStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrategies = channel.unary_unary(
                '/EvalPPO/GetStrategies',
                request_serializer=rpc_dot_RL__pb2.Observation.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Prediction.FromString,
                )
        self.AddExperience = channel.unary_unary(
                '/EvalPPO/AddExperience',
                request_serializer=rpc_dot_RL__pb2.SampledTrajectory.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.TrajectoriesLeft = channel.unary_unary(
                '/EvalPPO/TrajectoriesLeft',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.ResetBestResponse = channel.unary_unary(
                '/EvalPPO/ResetBestResponse',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class EvalPPOServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddExperience(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrajectoriesLeft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetBestResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvalPPOServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategies,
                    request_deserializer=rpc_dot_RL__pb2.Observation.FromString,
                    response_serializer=rpc_dot_RL__pb2.Prediction.SerializeToString,
            ),
            'AddExperience': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExperience,
                    request_deserializer=rpc_dot_RL__pb2.SampledTrajectory.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'TrajectoriesLeft': grpc.unary_unary_rpc_method_handler(
                    servicer.TrajectoriesLeft,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'ResetBestResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetBestResponse,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EvalPPO', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EvalPPO(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalPPO/GetStrategies',
            rpc_dot_RL__pb2.Observation.SerializeToString,
            rpc_dot_RL__pb2.Prediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddExperience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalPPO/AddExperience',
            rpc_dot_RL__pb2.SampledTrajectory.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrajectoriesLeft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalPPO/TrajectoriesLeft',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetBestResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalPPO/ResetBestResponse',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class EvalMCTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetValues = channel.unary_unary(
                '/EvalMCTS/GetValues',
                request_serializer=rpc_dot_RL__pb2.Observation.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.EvalPrediction.FromString,
                )
        self.AddValues = channel.unary_unary(
                '/EvalMCTS/AddValues',
                request_serializer=rpc_dot_RL__pb2.SampledEvalData.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.TrainValues = channel.unary_unary(
                '/EvalMCTS/TrainValues',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class EvalMCTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvalMCTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValues,
                    request_deserializer=rpc_dot_RL__pb2.Observation.FromString,
                    response_serializer=rpc_dot_RL__pb2.EvalPrediction.SerializeToString,
            ),
            'AddValues': grpc.unary_unary_rpc_method_handler(
                    servicer.AddValues,
                    request_deserializer=rpc_dot_RL__pb2.SampledEvalData.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'TrainValues': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainValues,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EvalMCTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EvalMCTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalMCTS/GetValues',
            rpc_dot_RL__pb2.Observation.SerializeToString,
            rpc_dot_RL__pb2.EvalPrediction.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalMCTS/AddValues',
            rpc_dot_RL__pb2.SampledEvalData.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EvalMCTS/TrainValues',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTraversals = channel.unary_unary(
                '/Master/RequestTraversals',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.ExitTraversalPool = channel.unary_unary(
                '/Master/ExitTraversalPool',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.GetPPOTableInstance = channel.unary_unary(
                '/Master/GetPPOTableInstance',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.TableMessage.FromString,
                )
        self.GetPPOCurrentIteration = channel.unary_unary(
                '/Master/GetPPOCurrentIteration',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.GetPPOTrainingWorkersLeft = channel.unary_unary(
                '/Master/GetPPOTrainingWorkersLeft',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.RequestPPOTrainingHands = channel.unary_unary(
                '/Master/RequestPPOTrainingHands',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.RequestPPOEvalHands = channel.unary_unary(
                '/Master/RequestPPOEvalHands',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.AddPPOEvalRewards = channel.unary_unary(
                '/Master/AddPPOEvalRewards',
                request_serializer=rpc_dot_RL__pb2.SampledRewards.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.ExitPPOTrainingPool = channel.unary_unary(
                '/Master/ExitPPOTrainingPool',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.ExitPPOEvaluationPool = channel.unary_unary(
                '/Master/ExitPPOEvaluationPool',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.RequestMCTSEvaluation = channel.unary_unary(
                '/Master/RequestMCTSEvaluation',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                )
        self.ExitMCTSEvaluationPool = channel.unary_unary(
                '/Master/ExitMCTSEvaluationPool',
                request_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.AddMCTSExploitabilitySample = channel.unary_unary(
                '/Master/AddMCTSExploitabilitySample',
                request_serializer=rpc_dot_RL__pb2.FloatMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestTraversals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitTraversalPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPPOTableInstance(self, request, context):
        """PPO Eval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPPOCurrentIteration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPPOTrainingWorkersLeft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPPOTrainingHands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPPOEvalHands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPPOEvalRewards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitPPOTrainingPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitPPOEvaluationPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMCTSEvaluation(self, request, context):
        """MCTS Eval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitMCTSEvaluationPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMCTSExploitabilitySample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTraversals': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTraversals,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'ExitTraversalPool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitTraversalPool,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'GetPPOTableInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPPOTableInstance,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.TableMessage.SerializeToString,
            ),
            'GetPPOCurrentIteration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPPOCurrentIteration,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'GetPPOTrainingWorkersLeft': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPPOTrainingWorkersLeft,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'RequestPPOTrainingHands': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPPOTrainingHands,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'RequestPPOEvalHands': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPPOEvalHands,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'AddPPOEvalRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPPOEvalRewards,
                    request_deserializer=rpc_dot_RL__pb2.SampledRewards.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'ExitPPOTrainingPool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitPPOTrainingPool,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'ExitPPOEvaluationPool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitPPOEvaluationPool,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'RequestMCTSEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMCTSEvaluation,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
            ),
            'ExitMCTSEvaluationPool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitMCTSEvaluationPool,
                    request_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'AddMCTSExploitabilitySample': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMCTSExploitabilitySample,
                    request_deserializer=rpc_dot_RL__pb2.FloatMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestTraversals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/RequestTraversals',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitTraversalPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/ExitTraversalPool',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPPOTableInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/GetPPOTableInstance',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.TableMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPPOCurrentIteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/GetPPOCurrentIteration',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPPOTrainingWorkersLeft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/GetPPOTrainingWorkersLeft',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPPOTrainingHands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/RequestPPOTrainingHands',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPPOEvalHands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/RequestPPOEvalHands',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddPPOEvalRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/AddPPOEvalRewards',
            rpc_dot_RL__pb2.SampledRewards.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitPPOTrainingPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/ExitPPOTrainingPool',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitPPOEvaluationPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/ExitPPOEvaluationPool',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestMCTSEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/RequestMCTSEvaluation',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.IntMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitMCTSEvaluationPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/ExitMCTSEvaluationPool',
            rpc_dot_RL__pb2.Empty.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddMCTSExploitabilitySample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master/AddMCTSExploitabilitySample',
            rpc_dot_RL__pb2.FloatMessage.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class SlaveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetIdentifier = channel.unary_unary(
                '/Slave/SetIdentifier',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.RunTraversals = channel.unary_unary(
                '/Slave/RunTraversals',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )
        self.RunEvaluations = channel.unary_unary(
                '/Slave/RunEvaluations',
                request_serializer=rpc_dot_RL__pb2.IntMessage.SerializeToString,
                response_deserializer=rpc_dot_RL__pb2.Empty.FromString,
                )


class SlaveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetIdentifier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTraversals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvaluations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlaveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetIdentifier': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIdentifier,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'RunTraversals': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTraversals,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
            'RunEvaluations': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEvaluations,
                    request_deserializer=rpc_dot_RL__pb2.IntMessage.FromString,
                    response_serializer=rpc_dot_RL__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Slave', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Slave(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetIdentifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Slave/SetIdentifier',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTraversals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Slave/RunTraversals',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunEvaluations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Slave/RunEvaluations',
            rpc_dot_RL__pb2.IntMessage.SerializeToString,
            rpc_dot_RL__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
